BolivarAssistence/config/routes.rb
Rails.application.routes.draw do
  resources :type_vehicles
  resources :insurance_policies
  resources :services
  resources :vehicles
  resources :owners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

BolivarAssistence/app/models/insurance_policy.rb
class InsurancePolicy < ApplicationRecord
end

BolivarAssistence/app/controllers/insurance_policies_controller.rb
class InsurancePoliciesController < ApplicationController
  before_action :set_insurance_policy, only: [:show, :edit, :update, :destroy]

  # GET /insurance_policies
  # GET /insurance_policies.json
  def index
    @insurance_policies = InsurancePolicy.all
  end

  # GET /insurance_policies/1
  # GET /insurance_policies/1.json
  def show
  end

  # GET /insurance_policies/new
  def new
    @insurance_policy = InsurancePolicy.new
  end

  # GET /insurance_policies/1/edit
  def edit
  end

  # POST /insurance_policies
  # POST /insurance_policies.json
  def create
    @insurance_policy = InsurancePolicy.new(insurance_policy_params)

    respond_to do |format|
      if @insurance_policy.save
        format.html { redirect_to @insurance_policy, notice: 'Insurance policy was successfully created.' }
        format.json { render :show, status: :created, location: @insurance_policy }
      else
        format.html { render :new }
        format.json { render json: @insurance_policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurance_policies/1
  # PATCH/PUT /insurance_policies/1.json
  def update
    respond_to do |format|
      if @insurance_policy.update(insurance_policy_params)
        format.html { redirect_to @insurance_policy, notice: 'Insurance policy was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance_policy }
      else
        format.html { render :edit }
        format.json { render json: @insurance_policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurance_policies/1
  # DELETE /insurance_policies/1.json
  def destroy
    @insurance_policy.destroy
    respond_to do |format|
      format.html { redirect_to insurance_policies_url, notice: 'Insurance policy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance_policy
      @insurance_policy = InsurancePolicy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_policy_params
      params.require(:insurance_policy).permit(:basic, :standard, :premium)
    end
end

BolivarAssistence/app/helpers/insurance_policies_helper.rb
module InsurancePoliciesHelper
end

BolivarAssistence/app/views/insurance_policies/_form.html.erb
<%= form_with(model: insurance_policy, local: true) do |form| %>
  <% if insurance_policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insurance_policy.errors.count, "error") %> prohibited this insurance_policy from being saved:</h2>

      <ul>
        <% insurance_policy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :basic %>
    <%= form.text_field :basic %>
  </div>

  <div class="field">
    <%= form.label :standard %>
    <%= form.text_field :standard %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.text_field :premium %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BolivarAssistence/app/views/insurance_policies/edit.html.erb
<h1>Editing Insurance Policy</h1>

<%= render 'form', insurance_policy: @insurance_policy %>

<%= link_to 'Show', @insurance_policy %> |
<%= link_to 'Back', insurance_policies_path %>

BolivarAssistence/app/views/insurance_policies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Insurance Policies</h1>

<table>
  <thead>
    <tr>
      <th>Basic</th>
      <th>Standard</th>
      <th>Premium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurance_policies.each do |insurance_policy| %>
      <tr>
        <td><%= insurance_policy.basic %></td>
        <td><%= insurance_policy.standard %></td>
        <td><%= insurance_policy.premium %></td>
        <td><%= link_to 'Show', insurance_policy %></td>
        <td><%= link_to 'Edit', edit_insurance_policy_path(insurance_policy) %></td>
        <td><%= link_to 'Destroy', insurance_policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance Policy', new_insurance_policy_path %>

BolivarAssistence/app/views/insurance_policies/new.html.erb
<h1>New Insurance Policy</h1>

<%= render 'form', insurance_policy: @insurance_policy %>

<%= link_to 'Back', insurance_policies_path %>

BolivarAssistence/app/views/insurance_policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Basic:</strong>
  <%= @insurance_policy.basic %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @insurance_policy.standard %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @insurance_policy.premium %>
</p>

<%= link_to 'Edit', edit_insurance_policy_path(@insurance_policy) %> |
<%= link_to 'Back', insurance_policies_path %>