BolivarAssistence/config/routes.rb
Rails.application.routes.draw do
  resources :type_vehicles
  resources :insurance_policies
  resources :services
  resources :vehicles
  resources :owners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

BolivarAssistence/app/models/type_vehicle.rb
class TypeVehicle < ApplicationRecord
end

BolivarAssistence/app/controllers/type_vehicles_controller.rb
class TypeVehiclesController < ApplicationController
  before_action :set_type_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /type_vehicles
  # GET /type_vehicles.json
  def index
    @type_vehicles = TypeVehicle.all
  end

  # GET /type_vehicles/1
  # GET /type_vehicles/1.json
  def show
  end

  # GET /type_vehicles/new
  def new
    @type_vehicle = TypeVehicle.new
  end

  # GET /type_vehicles/1/edit
  def edit
  end

  # POST /type_vehicles
  # POST /type_vehicles.json
  def create
    @type_vehicle = TypeVehicle.new(type_vehicle_params)

    respond_to do |format|
      if @type_vehicle.save
        format.html { redirect_to @type_vehicle, notice: 'Type vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @type_vehicle }
      else
        format.html { render :new }
        format.json { render json: @type_vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_vehicles/1
  # PATCH/PUT /type_vehicles/1.json
  def update
    respond_to do |format|
      if @type_vehicle.update(type_vehicle_params)
        format.html { redirect_to @type_vehicle, notice: 'Type vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_vehicle }
      else
        format.html { render :edit }
        format.json { render json: @type_vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_vehicles/1
  # DELETE /type_vehicles/1.json
  def destroy
    @type_vehicle.destroy
    respond_to do |format|
      format.html { redirect_to type_vehicles_url, notice: 'Type vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_vehicle
      @type_vehicle = TypeVehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_vehicle_params
      params.require(:type_vehicle).permit(:moto, :particularTourism, :bus, :furgon)
    end
end

BolivarAssistence/app/helpers/type_vehicles_helper.rb
module TypeVehiclesHelper
end

BolivarAssistence/app/views/type_vehicles/_form.html.erb
<%= form_with(model: type_vehicle, local: true) do |form| %>
  <% if type_vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_vehicle.errors.count, "error") %> prohibited this type_vehicle from being saved:</h2>

      <ul>
        <% type_vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :moto %>
    <%= form.text_field :moto %>
  </div>

  <div class="field">
    <%= form.label :particularTourism %>
    <%= form.text_field :particularTourism %>
  </div>

  <div class="field">
    <%= form.label :bus %>
    <%= form.text_field :bus %>
  </div>

  <div class="field">
    <%= form.label :furgon %>
    <%= form.text_field :furgon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BolivarAssistence/app/views/type_vehicles/edit.html.erb
<h1>Editing Type Vehicle</h1>

<%= render 'form', type_vehicle: @type_vehicle %>

<%= link_to 'Show', @type_vehicle %> |
<%= link_to 'Back', type_vehicles_path %>

BolivarAssistence/app/views/type_vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Moto</th>
      <th>Particulartourism</th>
      <th>Bus</th>
      <th>Furgon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_vehicles.each do |type_vehicle| %>
      <tr>
        <td><%= type_vehicle.moto %></td>
        <td><%= type_vehicle.particularTourism %></td>
        <td><%= type_vehicle.bus %></td>
        <td><%= type_vehicle.furgon %></td>
        <td><%= link_to 'Show', type_vehicle %></td>
        <td><%= link_to 'Edit', edit_type_vehicle_path(type_vehicle) %></td>
        <td><%= link_to 'Destroy', type_vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Vehicle', new_type_vehicle_path %>

BolivarAssistence/app/views/type_vehicles/new.html.erb
<h1>New Type Vehicle</h1>

<%= render 'form', type_vehicle: @type_vehicle %>

<%= link_to 'Back', type_vehicles_path %>

BolivarAssistence/app/views/type_vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Moto:</strong>
  <%= @type_vehicle.moto %>
</p>

<p>
  <strong>Particulartourism:</strong>
  <%= @type_vehicle.particularTourism %>
</p>

<p>
  <strong>Bus:</strong>
  <%= @type_vehicle.bus %>
</p>

<p>
  <strong>Furgon:</strong>
  <%= @type_vehicle.furgon %>
</p>

<%= link_to 'Edit', edit_type_vehicle_path(@type_vehicle) %> |
<%= link_to 'Back', type_vehicles_path %>